### ISSUE TITLE
model/bigram_word.txt 不存在

### ISSUE THREAD

**Issue by aenon** [lancopku/PKUSeg-python#1]
试图运行 Python 版
```
python3 main.py test a.txt out.txt
```
报错:
```
Traceback (most recent call last):
  File "main.py", line 316, in <module>
    run()
  File "main.py", line 17, in run
    testFeature = Feature(config.readFile, 'test')
  File "/Users/xilins/Personal/PKUSeg-python/feature.py", line 11, in __init__
    self.test_init()
  File "/Users/xilins/Personal/PKUSeg-python/feature.py", line 26, in test_init
    self.readBigramFeature(config.modelDir+'/bigram_word.txt')
  File "/Users/xilins/Personal/PKUSeg-python/feature.py", line 54, in readBigramFeature
    with open(file, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'model/bigram_word.txt'
```

**Comment by luoruixuan** [comment]
你需要在自己的数据集上进行训练或者下载我们提供的预训练模型并放到model目录下。下载链接见README.md。
