### ISSUE TITLE
词性标注模型加载报错

### ISSUE THREAD

**Issue by Yang-X-Y** [lancopku/pkuseg-python#100]
seg = pkuseg.pkuseg(postag=True)  # 开启词性标注功能
WARNING: features.pkl does not exist, try loading features.json
WARNING: features.json does not exist, try loading using old format
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/11103333/data/config/anaconda3/lib/python3.7/site-packages/pkuseg/__init__.py", line 234, in __init__
    self.tagger = Postag(postag_dir)
  File "/home/11103333/data/config/anaconda3/lib/python3.7/site-packages/pkuseg/postag/__init__.py", line 16, in __init__
    self.feature_extractor = FeatureExtractor.load(modelDir)
  File "pkuseg/postag/feature_extractor.pyx", line 318, in pkuseg.postag.feature_extractor.FeatureExtractor.load
FileNotFoundError: [Errno 2] No such file or directory: '/home/11103333/.pkuseg/postag/featureIndex.txt_0'

**Comment by liujshi** [comment]
unzip the download file

**Comment by hweidream** [comment]
> unzip the download file

请问是解压哪个文件
