### ISSUE TITLE
下载模型会超时

### ISSUE THREAD

**Issue by rickyhuw** [lancopku/pkuseg-python#111]
Downloading: "https://github.com/lancopku/pkuseg-python/releases/download/v0.0.16/web.zip" to /Users/ricky/.pkuseg/web.zip
  2%|▏         | 409600/17478354 [00:08<05:48, 48934.27it/s]
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 294, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1814, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/anaconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1614, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/anaconda3/lib/python3.7/site-packages/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/anaconda3/lib/python3.7/http/client.py", line 447, in read
    n = self.readinto(b)
  File "/anaconda3/lib/python3.7/http/client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "/anaconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/anaconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 307, in recv_into
    raise timeout('The read operation timed out')
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ricky/PycharmProjects/testProject/TheFirst/hhh.py", line 11, in <module>
    seg = pkuseg.pkuseg(user_dict=d,model_name='web')
  File "/anaconda3/lib/python3.7/site-packages/pkuseg/__init__.py", line 207, in __init__
    download_model(config.model_urls[model_name], config.pkuseg_home, config.model_hash[model_name])
  File "/anaconda3/lib/python3.7/site-packages/pkuseg/download.py", line 38, in download_model
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/anaconda3/lib/python3.7/site-packages/pkuseg/download.py", line 61, in _download_url_to_file
    buffer = u.read(8192)
  File "/anaconda3/lib/python3.7/site-packages/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/anaconda3/lib/python3.7/site-packages/urllib3/response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='github-production-release-asset-2e65be.s3.amazonaws.com', port=443): Read timed out.

**Comment by TIANRENK** [comment]
问题解决了吗

**Comment by rickyhuw** [comment]
多试几次就好了，网络抖动就会断，我是先下载到本地然后上传到服务器的。

**Comment by ZhiyiLan** [comment]
可以手动下载模型，解压后放到相应的目录即可

**Comment by pblh123** [comment]
> 可以手动下载模型，解压后放到相应的目录即可

通过下载时提示的url手动下载，再放到相应路径吗？

**Comment by 46319943** [comment]
可以自己下载然后解压放到相应目录里面。
对于ubuntu，位置是在~/.pkuseg/[模型名称文件夹]
或者修改下载部分的代码，给它添加代理。

**Comment by williamjin1992** [comment]
> 相应

请问相应的路径是哪一个？系统为macOS 10.15

**Comment by veinhao** [comment]
> 可以自己下载然后解压放到相应目录里面。 对于ubuntu，位置是在~/.pkuseg/[模型名称文件夹] 或者修改下载部分的代码，给它添加代理。

WIN11 不用解压，直接放在C盘用户下的.pkuseg的目录下

**Comment by rickyhuw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已被接受，我将尽快回复您！

**Comment by lcyyyyyyyyyyy** [comment]
***@***.***，本次回复为系统自动回复！
