### ISSUE TITLE
错误求帮助 FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wwe8866** [lancopku/pkuseg-python#115]
WARNING: features.pkl does not exist, try loading features.json
WARNING: features.json does not exist, try loading using old format
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/pytest/test.py", line 3, in <module>
    seg = pkuseg.pkuseg(postag=True)  # 开启词性标注功能
  File "C:\PY\Anaconda3\lib\site-packages\pkuseg\__init__.py", line 257, in __init__
    self.tagger = Postag(postag_dir)
  File "C:\PY\Anaconda3\lib\site-packages\pkuseg\postag\__init__.py", line 16, in __init__
    self.feature_extractor = FeatureExtractor.load(modelDir)
  File "pkuseg/postag/feature_extractor.pyx", line 318, in pkuseg.postag.feature_extractor.FeatureExtractor.load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator/.pkuseg\\postag\\featureIndex.txt_0'

**Comment by stephen-nju** [comment]
.pkuseg 下创建postag文件夹，将下载的文件解压到该文件夹下，我解决了这个问题

**Comment by isolet** [comment]
太垃圾了…

**Comment by hscspring** [comment]
设计的确恶心，有了解压文件，还必须保存着 zip 文件，要不然每次加载又要重新下载。
只能自己改了……

**Comment by cdj0311** [comment]
同样遇到这个问题，解决方法如下：
1. 下载postag.zip
2. 在~/.pkuseg下新建postag文件夹
3. 将postag.zip解压到postag中
4. 运行即可

注意：一定要解压到postag文件夹中
