### ISSUE TITLE
KeyError: 'unigram'

### ISSUE THREAD

**Issue by yuyonghao922** [lancopku/pkuseg-python#124]
import pkuseg
seg = pkuseg.pkuseg(model_name='./pkuseg_postag/')  # 开启词性标注功能
text = seg.cut('请帮我打开空调')    # 进行分词和词性标注
print(text)
报错如下：
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/smart_home_v4.0/test_pkuseg.py", line 3, in <module>
    seg = pkuseg.pkuseg(model_name='./pkuseg_postag/')  # 开启词性标注功能
  File "C:\Users\Administrator\Desktop\Python36_ASRT_2.0\lib\site-packages\pkuseg\__init__.py", line 241, in __init__
    self.feature_extractor = FeatureExtractor.load()
  File "pkuseg/feature_extractor.pyx", line 596, in pkuseg.feature_extractor.FeatureExtractor.load
KeyError: 'unigram'

**Comment by bifeng** [comment]
它这个封装的有问题 - 要使用词性标注，只需要设置一个参数就可以了（postag=True）

**Comment by hscspring** [comment]
自定义只针对了分词，对词性没用。
