### ISSUE TITLE
0.0.25在binder安装报错

### ISSUE THREAD

**Issue by GoooIce** [lancopku/pkuseg-python#131]
0.0.22 可以正常安装
```
Collecting numpy
  Downloading numpy-1.19.0-cp37-cp37m-manylinux2010_x86_64.whl (14.6 MB)
Collecting pkuseg
  Downloading pkuseg-0.0.25.tar.gz (48.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /srv/conda/envs/notebook/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5d95j8mq/pkuseg/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5d95j8mq/pkuseg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-h22vfd4x
         cwd: /tmp/pip-install-5d95j8mq/pkuseg/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5d95j8mq/pkuseg/setup.py", line 5, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by xiaxichen** [comment]
没有安装numpy

**Comment by doronzuker** [comment]
im having the same issue on 0.0.22 so i dont think this is the issue.
@GoooIce did you find a fix for the issue? i think its related to numpy installation of 1.19 did you by any chance update numpy as well when you updated to 0.25

**Comment by SagiMedina** [comment]
#141
