### ISSUE TITLE
AttributeError: type object 'pkuseg.inference.array' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by mafamily2496** [lancopku/pkuseg-python#44]
python3.7 导入的时候报错
AttributeError                            Traceback (most recent call last)
<ipython-input-71-1638147fbecb> in <module>
      5 from xgboost import XGBRegressor
      6 from sklearn import preprocessing
----> 7 import pkuseg
      8 import re
      9 from sklearn.feature_selection import SelectFromModel

/usr/local/anaconda3/lib/python3.7/site-packages/pkuseg/__init__.py in <module>
     12 from multiprocessing import Process, Queue
     13 
---> 14 import pkuseg.trainer
     15 import pkuseg.inference as _inf
     16 

/usr/local/anaconda3/lib/python3.7/site-packages/pkuseg/trainer.py in <module>
     17 # from .feature_generator import *
     18 from pkuseg.model import Model
---> 19 import pkuseg.inference as _inf
     20 
     21 # from .inference import *

/usr/local/anaconda3/lib/python3.7/site-packages/pkuseg/inference.cpython-37m-x86_64-linux-gnu.so in init pkuseg.inference()

AttributeError: type object 'pkuseg.inference.array' has no attribute '__reduce_cython__'

**Comment by RaymondLi1101** [comment]
遇到了一样的问题，3.6也是这个问题

**Comment by jingjingxupku** [comment]
> 遇到了一样的问题，3.6也是这个问题
> 第一次import提示
> ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
> 
> 再一次import就显示
> Traceback (most recent call last):
> File "", line 1, in 
> File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev_pydev_bundle\pydev_import_hook.py", line 20, in do_import
> module = self._system_import(name, *args, **kwargs) File "C:\Users\Lianyu Li\AppData\Local\Programs\Python\Python36\lib\site-packages\pkuseg__init__.py", line 14, in 
> import pkuseg.trainer as trainer
> File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev_pydev_bundle\pydev_import_hook.py", line 20, in do_import
> module = self._system_import(name, *args, **kwargs)
> File "C:\Users\Lianyu Li\AppData\Local\Programs\Python\Python36\lib\site-packages\pkuseg\trainer.py", line 19, in 
> import pkuseg.inference as _inf
> File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev_pydev_bundle\pydev_import_hook.py", line 20, in do_import
> module = self._system_import(name, *args, **kwargs)
> File "stringsource", line 105, in init pkuseg.inference
> AttributeError: type object 'pkuseg.inference.array' has no attribute '**reduce_cython**'

这条issue里面给出了可能的解决方案：https://github.com/lancopku/pkuseg-python/issues/38#issuecomment-456065828

**Comment by JosiaHung** [comment]
numpy   1.18.4不行，换成1.16.0成功运行
