### ISSUE TITLE
ValueError: 'pkuseg/inference.pyx' doesn't match any files 这个是撒子鬼哦 

### ISSUE THREAD

**Issue by lestinYin** [lancopku/pkuseg-python#45]
Lestin-MacBook-Pro:~ lestin.yin$ pip3 install -U pkuseg
Collecting pkuseg
  Using cached https://files.pythonhosted.org/packages/a5/83/5c6379ff4737bcd26ee1b5c83f2ae78b76651aa8ab1cd3ae1225329371fe/pkuseg-0.0.14.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y5/vr8wrq014hqclky244604c_r0000gn/T/pip-install-gekq4gpk/pkuseg/setup.py", line 48, in <module>
        setup_package()
      File "/private/var/folders/y5/vr8wrq014hqclky244604c_r0000gn/T/pip-install-gekq4gpk/pkuseg/setup.py", line 42, in setup_package
        ext_modules=cythonize(extensions, annotate=True),
      File "/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 920, in cythonize
        aliases=aliases)
      File "/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 800, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 125, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pkuseg/inference.pyx' doesn't match any files
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/y5/vr8wrq014hqclky244604c_r0000gn/T/pip-install-gekq4gpk/pkuseg/

**Comment by george-sq** [comment]
遇到同样的问题
![image](https://user-images.githubusercontent.com/17562116/51601978-c1205380-1f40-11e9-8050-f75c5a3e652d.png)

**Comment by ZHHJemotion** [comment]
@jingjingxupku nice work！！感谢感谢，前天还在为 mac 上安装差点挠破了头

**Comment by iofu728** [comment]
TF can't work on py3.6+. So please support py3.5🙊

**Comment by museless** [comment]
Fedora 23 x86-64 Python3.4.3 pip19.0.2
pip3.4 install pkuseg 0.0.13-0.0.15
都会报

```
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a5/83/5c6379ff4737bcd26ee1b5c83f2ae78b76651aa8ab1cd3ae1225329371fe/pkuseg-0.0.14.tar.gz (49.5MB)
    100% |████████████████████████████████| 49.5MB 730kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0o041v82/pkuseg/setup.py", line 48, in <module>
        setup_package()
      File "/tmp/pip-install-0o041v82/pkuseg/setup.py", line 42, in setup_package
        ext_modules=cythonize(extensions, annotate=True),
      File "/usr/lib64/python3.4/site-packages/Cython/Build/Dependencies.py", line 967, in cythonize
        aliases=aliases)
      File "/usr/lib64/python3.4/site-packages/Cython/Build/Dependencies.py", line 812, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/usr/lib64/python3.4/site-packages/Cython/Build/Dependencies.py", line 111, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pkuseg/inference.pyx' doesn't match any files
```

**Comment by museless** [comment]
Fedora 23 x86-64 / Python3.5.2 / pip19.0.2
```
Python 3.5.2 (default, Oct 21 2016, 21:58:07) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkuseg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/site-packages/pkuseg/__init__.py", line 14, in <module>
    import pkuseg.trainer as trainer
  File "/usr/lib64/python3.5/site-packages/pkuseg/trainer.py", line 15, in <module>
    from pkuseg.feature_extractor import FeatureExtractor
ImportError: /usr/lib64/python3.5/site-packages/pkuseg/feature_extractor.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

```

**Comment by museless** [comment]
Fedora 23 x86-64 / Python3.5.2 / pip19.0.2
pkuseg 0.0.13-0.0.15
```
Python 3.5.2 (default, Oct 21 2016, 21:58:07) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkuseg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/site-packages/pkuseg/__init__.py", line 14, in <module>
    import pkuseg.trainer as trainer
  File "/usr/lib64/python3.5/site-packages/pkuseg/trainer.py", line 15, in <module>
    from pkuseg.feature_extractor import FeatureExtractor
ImportError: /usr/lib64/python3.5/site-packages/pkuseg/feature_extractor.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
```

**Comment by boltomli** [comment]
macOS 上 python 3.7 可以 clone 下来 python3 setup.py build

**Comment by wangmengna** [comment]
python3.7遇到同样的错误
pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple pkuseg
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pkuseg
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/20/ab/8d51a1c54840c94b1f30a703f68696d6348632c223a8a9f227ee4900bef8/pkuseg-0.0.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\admin\AppData\Local\Temp\pip-install-g1w677oy\pkuseg\setup.py", line 53, in <module>
        setup_package()
      File "C:\Users\admin\AppData\Local\Temp\pip-install-g1w677oy\pkuseg\setup.py", line 47, in setup_package
        ext_modules=cythonize(extensions, annotate=True),
      File "d:\python37\lib\site-packages\Cython\Build\Dependencies.py", line 967, in cythonize
        aliases=aliases)
      File "d:\python37\lib\site-packages\Cython\Build\Dependencies.py", line 812, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "d:\python37\lib\site-packages\Cython\Build\Dependencies.py", line 111, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pkuseg/inference.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\admin\AppData\Local\Temp\pip-install-g1w677oy\pkuseg\

**Comment by ranglang** [comment]
same error with python 37 & mojave

**Comment by ChanYuan2** [comment]
Same error with python3.6.8, what's wrong with it?

**Comment by DLBob** [comment]
能否尽快提供win版本？

**Comment by wangmengna** [comment]
win10 64bit

**Comment by kururuken** [comment]
python3.6 macos mojave 依然报错

**Comment by xulimessage** [comment]
这个问题什么时候解决？

**Comment by yanwei** [comment]
python 3.7.2:
ValueError: 'pkuseg/inference.pyx' doesn't match any files

**Comment by jingjingxupku** [comment]
感谢大家的反馈，针对此问题，我们对新版本增加了更多系统的支持，目前共支持linux、windows 64、以及mac系统的python 3.5、python 3.6、和python 3.7版本，大家可以pip下载新版本使用。

**Comment by l1t1** [comment]
https://github.com/lancopku/pkuseg-python/issues/69
same question

**Comment by slashAmoment** [comment]
x86_64 anaconda3-5.3.1 still error

**Comment by Xili666** [comment]
win10 amd64 py3.7 error 'pkuseg/inference.pyx' doesn't match any files

**Comment by cloudhuang** [comment]
Ubuntu 19.04 Python3 has the same error:
```
ValueError: 'pkuseg/inference.pyx' doesn't match any files
```

**Comment by Siriuser** [comment]
win10 python 3.7  has the same error

**Comment by Dodotry** [comment]
看来这个问题不只是我一个人遇上了，有解决方法吗？

**Comment by hwaight** [comment]
我刚刚安装了pkuseg。最近的pkuseg 目录下文件是pkuseg/inference.pyk了。
我用：
1) Python 3.7
2) pip install cython 
3) pip install -U pkuseg --user 
pip3 不行。谢谢大家的建议。

**Comment by LeeYatSan** [comment]
MacOS 10.15.2 Python 3.8 has same error

**Comment by hwaight** [comment]
See my solution above.

**Comment by jokester** [comment]
pypi的 `pkuseg-0.0.22` tgz中仍然文件名不匹配.

自己clone repo是可以正常安装到本地的, 是不是可以考虑发个新版本到pip.

**Comment by usertomlin** [comment]
今天试出一个在python3.8用docker成功安装pkuseg 0.0.25的方法
Dockerfile的前7行改成如下的前7行，在ubuntu上安装pkuseg时能安装成功

(若是把Cython、numpy、pkuseg放到requirements.txt的话，
或者安装packages前没upgrade setuptools的话，
安装到pkuseg 0.0.25似乎都会失败)

-------------
**FROM python:3.8.8
WORKDIR /
COPY . /
RUN python -m pip install --upgrade setuptools
RUN pip install Cython==0.29.24
RUN pip install numpy==1.19.2
RUN pip install pkuseg==0.0.25**

RUN pip install -r requirements.txt
...
