### ISSUE TITLE
这个是什么问题导致的？

### ISSUE THREAD

**Issue by Fabyone** [lancopku/pkuseg-python#48]
length = 1 : 0
length = 2 : 2496
length = 3 : 2642
length = 4 : 2568
length = 5 : 1313
length = 6 : 633
length = 7 : 249
length = 8 : 133
length = 9 : 66
length = 10 : 16
length = 11 : 6
length = 12 : 1
length = 13 : 1

start training...

reading training & test data...
done! train/test data sizes: 1/1

r: 1
iter0  diff=1.00e+100  train-time(sec)=5.64  f-score=0.06%
iter1  diff=1.00e+100  train-time(sec)=5.63  f-score=0.00%
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    pkuseg.train('msr_training.utf8', 'msr_test_gold.utf8', './models', nthread=20)
  File "/Users/faby/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkuseg/__init__.py", line 324, in train
    trainer.train(config)
  File "/Users/faby/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkuseg/trainer.py", line 103, in train
    score_list = trainer.test(testset, i)
  File "/Users/faby/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkuseg/trainer.py", line 169, in test
    testset, self.model, writer
  File "/Users/faby/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkuseg/trainer.py", line 357, in _decode_fscore
    gold_tags, pred_tags, self.idx_to_chunk_tag
  File "/Users/faby/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkuseg/scorer.py", line 37, in getFscore
    pre = correct_chunk / res_chunk * 100
ZeroDivisionError: division by zero

**Comment by luoruixuan** [comment]
您好，看上去您的训练集和测试集大小均为1，可能是训练文件和测试文件格式有误。文件格式为一行一句话，每句中所有单词以单个或多个空格分开，建议您检查训练文件和测试文件。

**Comment by Fabyone** [comment]
多谢，已解决

**Comment by codeboywang** [comment]
> 您好，看上去您的训练集和测试集大小均为1，可能是训练文件和测试文件格式有误。文件格式为一行一句话，每句中所有单词以单个或多个空格分开，建议您检查训练文件和测试文件。

你好，训练中文语料，文件格式一行一句话，每局中的每个词语用单个或多个空格分开。是词语要分开对吗？例如：
中国矿业大学 位于 海淀区 的 学院路 上 。
这似乎需要很多的人工啊。

**Comment by Fan9** [comment]
同遇到这个问题， 训练集的样本数要大于10，不然就会报这个错误。 这是为了测试所以只给了几个样本。。。。
