### ISSUE TITLE
AttributeError: module 'tokenize' has no attribute 'generate_tokens'

### ISSUE THREAD

**Issue by kuoerwang** [lancopku/pkuseg-python#53]
# -- coding: utf-8 --

import pkuseg

seg = pkuseg.pkuseg()  # 以默认配置加载模型
text = seg.cut('我爱北京天安门')  # 进行分词
print(text)

Traceback (most recent call last):
  File "C:/Users/sinnus/NLP/Gideon/tokenize/model/tt.py", line 5, in <module>
    seg = pkuseg.pkuseg()  # 以默认配置加载模型
  File "C:\Users\sinnus\AppData\Local\Programs\Python\Python36\lib\site-packages\pkuseg\__init__.py", line 188, in __init__
    self.model = Model.load()
  File "C:\Users\sinnus\AppData\Local\Programs\Python\Python36\lib\site-packages\pkuseg\model.py", line 30, in load
    sizes = npz["sizes"]
  File "C:\Users\sinnus\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\npyio.py", line 258, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "C:\Users\sinnus\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\format.py", line 678, in read_array
    shape, fortran_order, dtype = _read_array_header(fp, version)
  File "C:\Users\sinnus\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\format.py", line 540, in _read_array_header
    header = _filter_header(header)
  File "C:\Users\sinnus\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\format.py", line 502, in _filter_header
    for token in tokenize.generate_tokens(StringIO(string).readline):
AttributeError: module 'tokenize' has no attribute 'generate_tokens'

**Comment by jingjingxupku** [comment]
如果是直接从github下载到本地的话，需要先使用python setup.py build_ext -i命令进行安装，安装成功后才可以调用pkuseg.pkuseg()。
