### ISSUE TITLE
python 3.6 AttributeError: type object 'pkuseg.inference.array' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by yaoz311** [lancopku/pkuseg-python#57]
python 3.6 导入时报错如下：

import pkuseg

Traceback (most recent call last):

  File "<ipython-input-8-b856a984ee61>", line 1, in <module>
    import pkuseg

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\pkuseg\__init__.py", line 14, in <module>
    import pkuseg.trainer as trainer

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\pkuseg\trainer.py", line 19, in <module>
    import pkuseg.inference as _inf

  File "stringsource", line 105, in init pkuseg.inference

AttributeError: type object 'pkuseg.inference.array' has no attribute '__reduce_cython__'

**Comment by jingjingxupku** [comment]
请问您是通过pip安装使用的最新版本吗？

**Comment by yaoz311** [comment]
@jingjingxupku 嗯 是的

**Comment by yaoz311** [comment]
@jingjingxupku 我安装的是pkuseg-0.0.15

**Comment by jingjingxupku** [comment]
请问您是基于什么系统安装的工具包？linux、windows、还是mac系统？

**Comment by yaoz311** [comment]
@jingjingxupku 我是基于Windows的系统安装的

**Comment by almiao** [comment]
我把pkuseg和numpy都更新到最新版本后，该问题就没再出现了。

**Comment by ZHHJemotion** [comment]
@jingjingxupku 我把 numpy 版本降到了1.16.0，报错还是 numpy 的问题，请问有什么解决方案的吗？

**Comment by ZHHJemotion** [comment]
@jingjingxupku 安装numpy 1.16.0的时候需要卸载之前的版本，已经可以在 macos 上使用pkuseg 0.0.15，但是新的版本0.0.16好像还是不适用于 macos
