### ISSUE TITLE
Python3.6和3.7都没有安装成功

### ISSUE THREAD

**Issue by robert6757** [lancopku/pkuseg-python#58]
Collecting pkuseg
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7a/1b/02009529ded81e2c8c63489f8f2f0b45fd1b93ff2813e241c222ab5b73af/pkuseg-0.0.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\YangSh\AppData\Local\Temp\pip-install-_xuofiqq\pkuseg\setup.py", line 48, in <module>
        setup_package()
      File "C:\Users\YangSh\AppData\Local\Temp\pip-install-_xuofiqq\pkuseg\setup.py", line 42, in setup_package
        ext_modules=cythonize(extensions, annotate=True),
      File "c:\python37\lib\site-packages\Cython\Build\Dependencies.py", line 967, in cythonize
        aliases=aliases)
      File "c:\python37\lib\site-packages\Cython\Build\Dependencies.py", line 812, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "c:\python37\lib\site-packages\Cython\Build\Dependencies.py", line 111, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pkuseg/inference.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\YangSh\AppData\Local\Temp\pip-install-_xuofiqq\pkuseg\

**Comment by robert6757** [comment]
报这个错误，请大家帮我看看。

**Comment by robert6757** [comment]
这个问题已经解决了，我最终还是没有用pip3的方式。而是把源码下载后，自己编译的。
