### ISSUE TITLE
python3.5 版本依然不好使

### ISSUE THREAD

**Issue by snakecy** [lancopku/pkuseg-python#68]
python3.5 版本依然不好使

```
WARNING: features.pkl does not exist, try loading features.json
WARNING: features.json does not exist, try loading using old format
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    seg = pkuseg.pkuseg(model_name='mixed')
  File "/home/zhousl/py3_venv/lib/python3.5/site-packages/pkuseg-0.0.21-py3.5-linux-x86_64.egg/pkuseg/__init__.py", line 217, in __init__
    self.feature_extractor = FeatureExtractor.load()
  File "pkuseg/feature_extractor.pyx", line 625, in pkuseg.feature_extractor.FeatureExtractor.load
FileNotFoundError: [Errno 2] No such file or directory: 'mixed/unigram_word.txt'
```

**Comment by jingjingxupku** [comment]
您好，这个问题并不是版本不支持导致的。您使用的mixed参数并不是支持的输入参数。如果您想用混合模型，您可以使用缺省值或者default，以下是接口介绍：

```
pkuseg.pkuseg(model_name = "default", user_dict = "default", postag = False)
	model_name		模型路径。
			        "default"，默认参数，表示使用我们预训练好的混合领域模型(仅对pip下载的用户)。
				"news", 使用新闻领域模型。
				"web", 使用网络领域模型。
				"medicine", 使用医药领域模型。
				"tourism", 使用旅游领域模型。
			        model_path, 从用户指定路径加载模型。
```

**Comment by 46319943** [comment]
It may indicate your model path is not correctly set. You can refer to this solution:
https://github.com/explosion/spaCy/discussions/7370#discussioncomment-6415339
