### ISSUE TITLE
install failed under python 3.5.2 32bit

### ISSUE THREAD

**Issue by l1t1** [lancopku/pkuseg-python#69]
```
D:\Python35-32>pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple pkuseg
Collecting pkuseg
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0f/c4/e9503aec66cc092ac1529d33242bd4f3763c0afbc4e82a27d6263c62845e/pkuseg-0
.0.21.tar.gz (48.7MB)
    100% |████████████████████████████████| 48.8MB 12kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\qiwang\AppData\Local\Temp\pip-build-cafm62l4\pkuseg\setup.py", line 5, in <module>
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\qiwang\AppData\Local\Temp\pip-build-cafm62l4\pkuseg\
```
and I installed Cython, but still cant install pkuseg
```
D:\Python35-32>pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -U Cython
Collecting Cython
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/33/6b/6558b0b0324396c3e9c88de8cd93eaeb492c6f5c8db34c6a742b8a46bc34/Cython-0
.29.6-cp35-cp35m-win32.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 182kB/s
Installing collected packages: Cython
Successfully installed Cython-0.29.6

D:\Python35-32>pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -U pkuseg
Collecting pkuseg
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0f/c4/e9503aec66cc092ac1529d33242bd4f3763c0afbc4e82a27d6263c62845e/pkuseg-
0.0.21.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\qiwang\AppData\Local\Temp\pip-build-ghducco1\pkuseg\setup.py", line 53, in <module>
        setup_package()
      File "C:\Users\qiwang\AppData\Local\Temp\pip-build-ghducco1\pkuseg\setup.py", line 47, in setup_package
        ext_modules=cythonize(extensions, annotate=True),
      File "d:\python35-32\lib\site-packages\Cython\Build\Dependencies.py", line 967, in cythonize
        aliases=aliases)
      File "d:\python35-32\lib\site-packages\Cython\Build\Dependencies.py", line 812, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "d:\python35-32\lib\site-packages\Cython\Build\Dependencies.py", line 111, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pkuseg/inference.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\qiwang\AppData\Local\Temp\pip-build-ghducco1\pkuseg\
```

**Comment by jingjingxupku** [comment]
您好，目前pkuseg仅支持mac，linux，windows 64位的python 3.5， 3.6，3.7版本，暂时还不支持windows 32位的系统。

**Comment by l1t1** [comment]
the err msg of tensorflow is better
```
D:\Python35-32>pip3 install tensorflow
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
```
