### ISSUE TITLE
AttributeError: 'list' object has no attribute 'copy'

### ISSUE THREAD

**Issue by jekin000** [lancopku/pkuseg-python#7]
hi ,  when I import the pkuseg, there seems something is wrong, please help check the issue.

>>> import pkuseg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pkuseg/__init__.py", line 2, in <module>
    from .config import Config
  File "/usr/local/lib/python2.7/dist-packages/pkuseg/config.py", line 174, in <module>
    config = Config()
  File "/usr/local/lib/python2.7/dist-packages/pkuseg/config.py", line 39, in __init__
    self.regList = self.regs.copy()
AttributeError: 'list' object has no attribute 'copy'

**Comment by worldwar2008** [comment]
>>> import pkuseg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkuseg/__init__.py", line 2, in <module>
    from .config import Config
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkuseg/config.py", line 174, in <module>
    config = Config()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkuseg/config.py", line 39, in __init__
    self.regList = self.regs.copy()
AttributeError: 'list' object has no attribute 'copy'

**Comment by HefeiLiu** [comment]
Ubuntu16 ，python 2.7下不能成功，在Python3.6下可以正常运行。

**Comment by Great223** [comment]
去"config.py" 第39行改成 “self.regList = [i for i in self.regs]”  然后第一行加上“# -*- coding: utf-8 -*- ”

**Comment by x-hacker** [comment]
Mac Python2.7报错AttributeError: 'list' object has no attribute 'copy'。。。。是不支持2.7么
