### ISSUE TITLE
install failed under python 3.6.7 win64

### ISSUE THREAD

**Issue by l1t1** [lancopku/pkuseg-python#70]
```
C:\Users\lutao>cd \python36

C:\Python36>cd scripts

C:\Python36\Scripts>pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -U Cython
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting Cython
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ab/dd/e9284aa584cb9f4b598af88c60e56a199f915b9105d0b747d16ddbfd5
1a0/Cython-0.29.6-cp36-cp36m-win_amd64.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 3.3MB/s
tensorflow-gpu 1.11.0 has requirement tensorboard<1.12.0,>=1.11.0, but you'll have tensorboard 1.12.0 which is incompati
ble.
Installing collected packages: Cython
  The scripts cygdb.exe, cython.exe and cythonize.exe are installed in 'c:\python36\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Cython-0.29.6
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Python36\Scripts>pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple pkuseg
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pkuseg
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/28/e7/fa07a9665e564853b7296240fa0f1c70b444db168b57ad38ca4e953fe
5a5/pkuseg-0.0.21-cp36-cp36m-win_amd64.whl (49.2MB)
    100% |████████████████████████████████| 49.2MB 298kB/s
Collecting numpy>=1.16.0 (from pkuseg)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ed/29/d97b6252591da5f8add0d25eecda296ea72729a0aad7998edba1981b4
7c8/numpy-1.16.2-cp36-cp36m-win_amd64.whl (11.9MB)
    100% |████████████████████████████████| 11.9MB 82kB/s
tensorflow-gpu 1.11.0 has requirement tensorboard<1.12.0,>=1.11.0, but you'll have tensorboard 1.12.0 which is incompati
ble.
Installing collected packages: numpy, pkuseg
  Found existing installation: numpy 1.15.3
    Uninstalling numpy-1.15.3:
      Successfully uninstalled numpy-1.15.3
  Rolling back uninstall of numpy
Could not install packages due to an EnvironmentError: [Errno 28] No space left on device: 'c:\\python36\\lib\\site-pack
ages\\numpy-1.15.3.dist-info\\metadata'

You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Python36\Scripts>pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple pkuseg
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pkuseg
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/28/e7/fa07a9665e564853b7296240fa0f1c70b444db168b57ad38ca4e953f
e5a5/pkuseg-0.0.21-cp36-cp36m-win_amd64.whl
Collecting numpy>=1.16.0 (from pkuseg)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ed/29/d97b6252591da5f8add0d25eecda296ea72729a0aad7998edba1981b
47c8/numpy-1.16.2-cp36-cp36m-win_amd64.whl
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'c:\\python36\\lib\\site-pac
kages\\numpy-1.15.3.dist-info\\METADATA'

You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by l1t1** [comment]
```
C:\Python36\Scripts>cd ..

C:\Python36>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
ImportError: cannot import name 'core'
```

**Comment by l1t1** [comment]
I rename the numpy-1.15.3.dist-info folder to numpy-1.15.3.dist-info.old, seems worked

```
C:\Python36\Scripts>pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple pkuseg
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pkuseg
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/28/e7/fa07a9665e564853b7296240fa0f1c70b444db168b57ad38ca4e953f
e5a5/pkuseg-0.0.21-cp36-cp36m-win_amd64.whl
Collecting numpy>=1.16.0 (from pkuseg)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ed/29/d97b6252591da5f8add0d25eecda296ea72729a0aad7998edba1981b
47c8/numpy-1.16.2-cp36-cp36m-win_amd64.whl
tensorflow-gpu 1.11.0 has requirement tensorboard<1.12.0,>=1.11.0, but you'll have tensorboard 1.12.0 which is incompati
ble.
Installing collected packages: numpy, pkuseg
  The script f2py.exe is installed in 'c:\python36\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.16.2 pkuseg-0.0.21
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
C:\Python36\Scripts>cd ..

C:\Python36>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
```
