### ISSUE TITLE
what is the required encode of input file?

### ISSUE THREAD

**Issue by l1t1** [lancopku/pkuseg-python#71]
```
C:\Python36>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import pkuseg
>>>
>>> seg = pkuseg.pkuseg()           # 以默认配置加载模型
>>> text = seg.cut('我爱北京天安门')  # 进行分词
>>> print(text)
['我', '爱', '北京', '天安门']
>>> import pkuseg
>>>
>>> seg = pkuseg.pkuseg(postag=True)  # 开启词性标注功能
Downloading: "https://github.com/lancopku/pkuseg-python/releases/download/v0.0.16/postag.zip" to C:\Users\lutao/.pkuseg\
postag.zip
100.0%
>>> text = seg.cut('我爱北京天安门')    # 进行分词和词性标注
>>> print(text)
[('我', 'r'), ('爱', 'v'), ('北京', 'ns'), ('天安门', 'ns')]
>>> import pkuseg
>>>
>>> # 对input.txt的文件分词输出到output.txt中
... # 开20个进程
... pkuseg.test('c:/user/lutao/downloads/0309a.txt', ''c:/user/lutao/downloads/0309a_output.txt', nthread=10)
  File "<stdin>", line 3
    pkuseg.test('c:/user/lutao/downloads/0309a.txt', ''c:/user/lutao/downloads/0309a_output.txt', nthread=10)
                                                       ^
SyntaxError: invalid syntax
>>> pkuseg.test('c:/user/lutao/downloads/0309a.txt', 'c:/user/lutao/downloads/0309a_output.txt', nthread=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\pkuseg\__init__.py", line 520, in test
    input_file, output_file, nthread, model_name, user_dict, postag, verbose
  File "C:\Python36\lib\site-packages\pkuseg\__init__.py", line 444, in _test_multi_proc
    raise Exception("input_file {} does not exist.".format(input_file))
Exception: input_file c:/user/lutao/downloads/0309a.txt does not exist.
```
I replaced '/' with '\', and encode of 0309a.txt is gbk
```
>>> pkuseg.test('c:\user\lutao\downloads\0309a.txt', 'c:\user\lutao\downloads\0309a_output.txt', nthread=10)
  File "<stdin>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \uXXXX escape
```
I save 0309a.txt to 0309b.txt as utf-8 encode,
```
>>> pkuseg.test('c:\user\lutao\downloads\0309b.txt', 'c:\user\lutao\downloads\0309b_output.txt', nthread=10)
  File "<stdin>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \uXXXX escape
```

**Comment by l1t1** [comment]
th 1-3 byte of 0309b.txt is EFBBBF, the utf-8 bom

**Comment by l1t1** [comment]
works using following code, the correct path delimeter is '/', \ufeff is treat as a word
```
>>> with open("c:/users/lutao/downloads/wabjtam.txt", encoding="utf-8") as f:
...     content = f.read()
...
>>> seg = pkuseg.pkuseg()
>>> text = seg.cut(content)
>>> counter = Counter(text)
>>> pprint.pprint(counter.most_common(20))
[('\ufeff', 1), ('我', 1), ('爱', 1), ('北京', 1), ('天安门', 1)]
```

**Comment by l1t1** [comment]
```
>>> pkuseg.test('c:/users/lutao/downloads/0309b.txt', 'c:/users/lutao/downloads/0309aboutput.txt', nthread=10)
total_time:     121.119
>>> pkuseg.test('c:/users/lutao/downloads/0309b.txt', 'c:/users/lutao/downloads/0309boutput.txt', nthread=1)
total_time:     4.243
```

**Comment by jingjingxupku** [comment]
"UTF8 without BOM"

**Comment by l1t1** [comment]
thanks
