### ISSUE TITLE
import pkuseg.inference as _inf, ImportError: DLL load failed: 找不到指定的模块

### ISSUE THREAD

**Issue by JungleXia** [lancopku/pkuseg-python#83]
# import pkuseg.inference as _inf, ImportError: DLL load failed: 找不到指定的模块

Installation Environment：
Window7、python3.7

I followed the tutorial installation and I got an error when I ran the first example.The Error:
Traceback (most recent call last):
  File "F:/Pywork/pyppe/agent_pyq/test_pkuseg.py", line 7, in <module>
    import pkuseg
  File "D:\ProgramData\Anaconda3\envs\pyppeteer\lib\site-packages\pkuseg\__init__.py", line 15, in <module>
    import pkuseg.trainer as trainer
  File "D:\ProgramData\Anaconda3\envs\pyppeteer\lib\site-packages\pkuseg\trainer.py", line 19, in <module>
    import pkuseg.inference as _inf
ImportError: DLL load failed: 找不到指定的模块。
![pkuseg](https://user-images.githubusercontent.com/24886531/56359269-a6920980-6213-11e9-873f-d24de52403c5.png)

**Comment by JadeQi** [comment]
请问了你解决了吗，我也遇到了同样的问题
