### ISSUE TITLE
安装的时候出现下面这个错误

### ISSUE THREAD

**Issue by Warriorwithdreams** [lancopku/pkuseg-python#85]
```
Collecting pkuseg
  Using cached https://files.pythonhosted.org/packages/0f/c4/e9503aec66cc092ac1529d33242bd4f3763c0afbc4e82a27d6263c62845e/pkuseg-0.0.21.tar.gz

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x04893990>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。',)': /simple/pkuseg/
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\86144\AppData\Local\Temp\pycharm-packaging\pkuseg\setup.py", line 5, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\86144\AppData\Local\Temp\pycharm-packaging\pkuseg\

```

**Comment by yaping03** [comment]
这几个文件后缀是.cpp
