### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'postag/unigram_word.txt'

### ISSUE THREAD

**Issue by jiangzhonglian** [lancopku/pkuseg-python#90]
```
import pkuseg

seg = pkuseg.pkuseg(model_name="postag")  # 程序会自动下载所对应的细领域模型
text = seg.cut('我爱北京天安门')              # 进行分词
print(text)
```

WARNING: features.pkl does not exist, try loading features.json
WARNING: features.json does not exist, try loading using old format
Traceback (most recent call last):
  File "src/tmp_pkuseg.py", line 4, in <module>
    seg = pkuseg.pkuseg(model_name="postag")  # 程序会自动下载所对应的细领域模型
  File "/Users/jiangzl/.virtualenvs/python3.6/lib/python3.6/site-packages/pkuseg/__init__.py", line 241, in __init__
    self.feature_extractor = FeatureExtractor.load()
  File "pkuseg/feature_extractor.pyx", line 625, in pkuseg.feature_extractor.FeatureExtractor.load
FileNotFoundError: [Errno 2] No such file or directory: 'postag/unigram_word.txt'

**Comment by nick-lee** [comment]
I got this problem as well, this package doesn't work on some version of python. finally, I try python 3.6.0 again , it passed!

**Comment by X-CCS** [comment]
I try python 3.6.0, but it didn't passed!

**Comment by bifeng** [comment]
它这个封装的有问题 - 要使用词性标注，只需要设置一个参数就可以了（postag=True），提供模型路径会报错
